# Programmieraufgabe 1: (gedämpftes) Newton-Verfahren

**Abgabe in den Programmiertutorien am 14. und 15. Mai 2025.**

Benötigte Module für dieses Notebook:

In [1]:
import numpy as np

In diesem Notebook wollen wir das Newton-Verfahren und das gedämpfte Newton-Verfahren zur Approximation einer Nullstelle der Funktion
$$f: \mathbb{R}^2 \to \mathbb{R}^2, \quad x = (x_1,x_2) \mapsto \begin{pmatrix} 1 - \frac{2}{\exp(x_1-x_2)+1} \\ x_2^3 + x_2 -2 \end{pmatrix}$$
testen.

**(a) Schreiben Sie jeweils eine Prozedur, die für einen Vektor $x\in\mathbb{R}^2$ die Funktion bzw. deren Ableitung an der Stelle $x$ berechnet und als `numpy`-array zurückgibt.**

In [2]:
def function(x):
    return np.array([1-2/(np.exp(x[0]-x[1])+1), x[1]**3+x[1]-2])

In [3]:
def jacobian(x):
    return np.array([
        [2*np.exp(x[0]-x[1])/(np.exp(x[0]-x[1])+1)**2, -2*np.exp(x[0]-x[1])/(np.exp(x[0]-x[1])+1)**2],
        [0, 3*x[1]**2+1]
    ])

**(b) Schreiben Sie eine Prozedur, die das Newton-Verfahren mit den in der Vorlesung besprochenen Kovergenz- und Abbruchkriterien auf eine Funktion $f:\mathbb{R}^n \to \mathbb{R}^n$ für beliebiges $n\in\mathbb{N}$ anwendet.**

Ihrer Prozedur soll folgende Eingabedaten haben:
- Einen Vektor `x0`, der den Startwert $x^{(0)}\in\mathbb{R}^n$ für das Newton-Verfahren enthält.
- Zwei Prozeduren `f` und `fprime`, mit denen Funktions- und Ableitungswerte von $f$ berechnet werden können.
- Eine Toleranz `tol` und eine maximale Zahl an Iterationen `kMax`, mit denen die Konvergenz- und Abbruchkriterien gesteuert werden können.

Berücksichtigen Sie außerdem folgendes:
- Die im Newton-Verfahren auftretenden Gleichungssysteme können Sie mit dem in `numpy` enthaltenen LGS-Löser `np.linalg.solve` lösen.
- Am Ende der Prozedur sollen alle berechneten Iterierten $x^{(k)}$, $k=0,1,2,...$ an das Hauptprogramm zurückgegeben werden. Geben Sie außerdem eine Meldung aus, ob das Verfahren erfolgreich konvergiert ist, oder ob es wegen Divergenz bzw. wegen Erreichen der maximalen Iterationszahl abgebrochen hat.

_Hinweis:_ Sie können alle Iterierten zum Beispiel als Zeilen in einer gemeinsamen Matrix speichern. Jedes Mal, wenn eine neue Iterierte berechnet wurde, wird die Matrix dementsprechend um eine Zeile ergänzt. Dazu ist der Befehl `np.vstack` hilfreich. Beispielsweise werden drei Matrizen `A1,A2,A3` derselben Breite mit dem Aufruf `np.vstack((A1,A2,A3))` übereinander gestapelt.

In [4]:
def newton_method(x0, f, fprime, tol, max_iter):
    x = x0
    x_ks = [x0]
    iter_count = 0
    pre_delta_norm = np.inf
    while iter_count < max_iter:
        iter_count += 1
        J = fprime(x)
        F = f(x)
        try:
            delta_x = np.linalg.solve(J, -F)
        except np.linalg.LinAlgError:
            print(f"Derivative is singular matrix. Exiting after {iter_count} iterations.")
            return np.vstack(x_ks)

        # check for divergence
        if (pre_delta_norm != np.inf and np.linalg.norm(delta_x) > pre_delta_norm):
            print(f"Diverged in {iter_count} iterations.")
            return np.vstack(x_ks)

        pre_delta_norm = np.linalg.norm(delta_x)
        x = x + delta_x
        x_ks.append(x)

        # check for convergence
        if (np.linalg.norm(delta_x) <= tol):
            print(f"Converged in {iter_count} iterations.")
            return np.vstack(x_ks)

    print(f"Max iterations reached ({max_iter}).")
    return np.vstack(x_ks)

**(c) Testen Sie Ihre Prozedur für die obige Funktion $f$ mit den Startvektoren $x^{(0)} = (4,2)^T$ und $x^{(0)} = (4,-4)^T$. Verwenden Sie die Parameter `tol = 1e-8` und `kMax = 20`.**

Geben Sie alle Iterierten aus. Für welchen Startvektor konvergiert das Verfahren? Vergewissern Sie sich im Falle der Konvergenz anhand der Funktionsvorschrift von $f$, dass Sie tatsächlich eine Nullstelle von $f$ erhalten haben. Geben Sie in dem Fall auch den Fehler der einzelnen Iterierten aus. Können Sie die erwartete, quadratische Konvergenz erkennen?

Startwert $x^{(0)} = (4,2)^T$:

In [5]:
newton_method(np.array([4, 2]), function, jacobian, 1e-8, 20)

Converged in 6 iterations.


array([[ 4.        ,  2.        ],
       [-0.24224502,  1.38461538],
       [ 1.90139076,  1.08258613],
       [ 0.91017052,  1.00478035],
       [ 1.00015828,  1.00001707],
       [ 1.        ,  1.        ],
       [ 1.        ,  1.        ]])

Startwert $x^{(0)} = (4,-4)^T$:

In [6]:
newton_method(np.array([4, -4]), function, jacobian, 1e-8, 20)

Derivative is singular matrix. Exiting after 2 iterations.


array([[    4.        ,    -4.        ],
       [-1485.05025436,    -2.57142857]])

**(d) Kopieren Sie das Newton-Verfahren von oben und ändern Sie es zum gedämpften Newton-Verfahren ab. Der Parameter $\lambda_{\min}$ soll dabei als zusätzlicher Eingabeparameter übergeben werden, während im ersten Schritt immer mit dem Wert $\lambda = 1$ gestartet wird. Geben Sie zusätzlich zu den Iterierten auch die verwendeten Dämpungsparameter an das Hauptprogramm zurück.**

_Hinweis:_ Das Schlüsselwort `lambda` hat in Python eine ganz besondere Bedeutung und sollte daher nicht als Variablenname genutzt werden.

In [27]:
# CONTINUE HERE

def dampened_newton_method(x0, f, fprime, tol, max_iter, damp_min):
    x = x0
    x_ks = [x0]
    iter_count = 0
    damp = 1.0
    damp_ks = [damp]
    delta_x_k = 2*tol*np.ones(x0.shape)
    while np.linalg.norm(delta_x_k) > tol and iter_count < max_iter:
        iter_count += 1
        J = fprime(x)
        F = f(x)
        try:
            delta_x_k = np.linalg.solve(J, -F)
        except np.linalg.LinAlgError:
            print(f"Derivative is singular matrix. Exiting after {iter_count} iterations.")
            return (np.vstack(x_ks), np.vstack(damp_ks))

        F_step = f(x + damp * delta_x_k)

        try:
            delta_x_bar = np.linalg.solve(J, -F_step)
        except np.linalg.LinAlgError:
            print(f"Derivative is singular matrix. Exiting after {iter_count} iterations.")
            return (np.vstack(x_ks), np.vstack(damp_ks))
        
        # refine dampening parameter
        while np.linalg.norm(delta_x_bar) > (1-damp*0.5)*np.linalg.norm(delta_x_k):
            damp *= 0.5
            if damp < damp_min:
                print(f"Dampening parameter too small. Exiting after {iter_count} iterations.")
                return (np.vstack(x_ks), np.vstack(damp_ks))
            F_step = f(x + damp * delta_x_k)
            try:
                delta_x_bar = np.linalg.solve(J, -F_step)
            except np.linalg.LinAlgError:
                print(f"Derivative is singular matrix. Exiting after {iter_count} iterations.")
                return (np.vstack(x_ks), np.vstack(damp_ks))

        x = x + damp * delta_x_k
        damp_ks.append(damp)
        damp = min(damp * 2, 1.0)
        x_ks.append(x)

        # check for convergence
        if (np.linalg.norm(delta_x_k) <= tol):
            print(f"Converged in {iter_count} iterations.")
            return (np.vstack(x_ks), np.vstack(damp_ks))

    print(f"Max iterations reached ({max_iter}).")
    return (np.vstack(x_ks), np.vstack(damp_ks))



**(e) Wiederholen Sie Teil (c) mit dem gedämpften Newton-Verfahren. Verwenden Sie dabei $\lambda_{\min}=10^{-10}$ und geben Sie die Werte des Dämpungsparameters aus.**

Startwert $x^{(0)} = (4,2)^T$:

In [28]:
dampened_newton_method(np.array([4, 2], dtype=np.float64), function, jacobian, 1e-8, 20, 1e-10)

Converged in 7 iterations.


(array([[4.        , 2.        ],
        [1.87887749, 1.69230769],
        [1.21801128, 1.21909553],
        [1.0302355 , 1.0302355 ],
        [1.00066867, 1.00066867],
        [1.00000034, 1.00000034],
        [1.        , 1.        ],
        [1.        , 1.        ]]),
 array([[1. ],
        [0.5],
        [1. ],
        [1. ],
        [1. ],
        [1. ],
        [1. ],
        [1. ]]))

Startwert $x^{(0)} = (4,-4)^T$:

In [29]:
dampened_newton_method(np.array([4, -4], dtype=np.float64), function, jacobian, 1e-8, 20, 1e-10)

Converged in 15 iterations.


(array([[ 4.        , -4.        ],
        [-7.63320511, -3.98883929],
        [-7.31224568, -3.9665702 ],
        [-6.82503331, -3.92224069],
        [-6.16938737, -3.83441038],
        [-5.35746869, -3.66201729],
        [-4.36717242, -3.32991961],
        [-3.13385084, -2.71335509],
        [-1.63142036, -1.64392215],
        [-0.75601228, -0.75601195],
        [ 0.41839333,  0.41839333],
        [ 0.91288792,  0.91288792],
        [ 1.00612654,  1.00612654],
        [ 1.00002801,  1.00002801],
        [ 1.        ,  1.        ],
        [ 1.        ,  1.        ]]),
 array([[1.       ],
        [0.0078125],
        [0.015625 ],
        [0.03125  ],
        [0.0625   ],
        [0.125    ],
        [0.25     ],
        [0.5      ],
        [1.       ],
        [1.       ],
        [1.       ],
        [0.5      ],
        [1.       ],
        [1.       ],
        [1.       ],
        [1.       ]]))