# Notebook zu Potenzenmethode & Rayleigh-Quotienten-Iteration

In [61]:
import numpy as np
import scipy.linalg as spla

Wir betrachten die Matrizen
$$
A = \begin{pmatrix} 5 & 4 & 4 & 5 \\ 9 & 4 & 8 & 3 \\ -9 & -4 & -8 & -5 \\ 0 & 1 & 1 & 2 \end{pmatrix} \qquad \text{und} \qquad
B = \begin{pmatrix} 5 & 4 & 4 & 5 \\ 6 & 4 & 5 & 3 \\ -6 & -4 & -5 & -5 \\ 0 & 1 & 1 & 2 \end{pmatrix}.
$$
Anhand dieser Matrizen wollen wir die Verfahren zur Approximation von Eigenwerten testen und verstehen. 

**(a) Um die Ergebnisse der Verfahren später beurteilen zu können, lassen Sie sich von Python zunächst die "korrekten" Eigenwerte berechnen und anzeigen. Benutzen Sie dazu den Befehl `eig` aus dem `linalg` Modul von `scipy`. Da dieses Modul oben mit dem Namen `spla` eingebunden wurde, wird der Befehl also über `spla.eig(...)` aufgerufen.**

In [62]:
A = np.array([[5.0, 4, 4, 5],[9, 4, 8, 3],[-9, -4, -8, -5],[0, 1, 1, 2]])
B = np.array([[5.0, 4, 4, 5],[6, 4, 5, 3],[-6, -4, -5, -5],[0, 1, 1, 2]])
print(A)
print(B)

[[ 5.  4.  4.  5.]
 [ 9.  4.  8.  3.]
 [-9. -4. -8. -5.]
 [ 0.  1.  1.  2.]]
[[ 5.  4.  4.  5.]
 [ 6.  4.  5.  3.]
 [-6. -4. -5. -5.]
 [ 0.  1.  1.  2.]]


In [63]:
print(spla.eig(A))
print(spla.eig(B))

(array([ 5.+0.j, -4.+0.j,  1.+1.j,  1.-1.j]), array([[ 5.77350269e-01+0.00000000e+00j,  1.92296269e-16+0.00000000e+00j,
        -1.59594560e-16-5.00000000e-01j, -1.59594560e-16+5.00000000e-01j],
       [ 5.77350269e-01+0.00000000e+00j, -7.07106781e-01+0.00000000e+00j,
        -5.00000000e-01+0.00000000e+00j, -5.00000000e-01-0.00000000e+00j],
       [-5.77350269e-01+0.00000000e+00j,  7.07106781e-01+0.00000000e+00j,
         1.38777878e-16+5.00000000e-01j,  1.38777878e-16-5.00000000e-01j],
       [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         5.00000000e-01-1.04083409e-16j,  5.00000000e-01+1.04083409e-16j]]))
(array([ 5.+0.j, -1.+0.j,  1.+1.j,  1.-1.j]), array([[ 5.77350269e-01+0.00000000e+00j, -6.40987562e-17+0.00000000e+00j,
         4.99600361e-16+5.00000000e-01j,  4.99600361e-16-5.00000000e-01j],
       [ 5.77350269e-01+0.00000000e+00j,  7.07106781e-01+0.00000000e+00j,
         5.00000000e-01+0.00000000e+00j,  5.00000000e-01-0.00000000e+00j],
       [-5.7

## Potenzenmethode

**(b) Schreiben Sie eine Prozedur, die `K` Iterationen der Potenzenmethode für eine Matrix `A` und einen Startvektor `z0` berechnet. Die Prozedur soll die aktuelle Approximation an den Eigenwert in jedem Schritt auf dem Bildschirm ausgeben, und am Ende die finale Approximationen an den Eigenwert und den Eigenvektor an das Hauptprogramm zurückgeben.**

**Hinweis:** Das komplexe Skalarprodukt $x^H y = \overline{x}^T y$ zweier Vektoren $x$ und $y$ erhalten Sie in numpy durch `np.vdot(x,y)`.

Außerdem ein kleiner Tipp, _falls_ Sie an einer schönen Bildschrimausgabe interessiert sind: In sogenannten "F-Strings" können Sie die Darstellung von Zahlen in Strings (also z.B. für den `print`-Befehl) beeinflussen. Ein Beispiel:

In [64]:
a = np.sqrt(2) 
print('Die Variable hat den Wert',a)
print(f'Die Variable hat den Wert {a:.3f}')

Die Variable hat den Wert 1.4142135623730951
Die Variable hat den Wert 1.414


In der zweiten Variante wurde die Darstellung der in `a` gespeicherten Zahl spezifiziert. Das führende `f` vor dem String erlaubt solche Formatierungen. Die geschweiften Klammern stellen einen Platzhalter für eine Zahl, die formatiert ausgegeben werden soll, dar. Vor dem Doppelpunkt wird angegeben, welche Variable ausgegeben werden soll, und dahinter wird spezifiziert in welcher Darstellung. Das `f` steht für eine Fix point number (das Komma trennt also immer den ganzahligen Teil von dem Rest). Der Zusatz `.3` legt genauer fest, dass 3 Nachkommastellen nach dem Dezimalpunkt angezeigt werden sollen.

In [65]:
def rayleigh_quot(A, v):
    return 1/np.vdot(v, v) * np.vdot(v, A @ v)

def power_iteration(K, A, z0):
    y_k = 1/spla.norm(z0) * z0
    z_k = y_k
    k = 0
    while k < K:
        z_k = A @ y_k
        q_k = np.vdot(y_k, z_k)
        y_k = 1/spla.norm(z_k) * z_k
        k += 1
        print(f'Rayleigh Quotient: {q_k:.3f} ({k} iterations)')
    return q_k, y_k

        

**(c) Testen Sie die Prozedur mit den obigen Matrizen $A$ und $B$. Starten Sie dabei mit einem beliebigen Vektor, z.B. $z_0 = (1,1,1,1)^T$, und berechnen Sie 30 Iterationen. Gegen welchen Eigenwert von $A$ bzw. $B$ konvergiert die Methode, und warum? Vergleichen und erklären Sie die Konvergenzgeschwindigkeiten. Überprüfen Sie außerdem den Fehler der finalen Approximationen $\lambda,v$ an Eigenwert und Eigenvektor, indem Sie den Wert von $\left\lVert Av-\lambda v \right\rVert_2$ für die jeweilige Matrix ausgeben.**

In [66]:
eig_val_A, eig_vec_A = power_iteration(30, A, np.array([1, 1, 1, 1]))
print('---')
eig_val_B, eig_vec_B = power_iteration(30, B, np.array([1, 1, 1, 1]))


Rayleigh Quotient: 5.000 (1 iterations)
Rayleigh Quotient: 3.246 (2 iterations)
Rayleigh Quotient: 7.040 (3 iterations)
Rayleigh Quotient: 3.604 (4 iterations)
Rayleigh Quotient: 6.271 (5 iterations)
Rayleigh Quotient: 4.072 (6 iterations)
Rayleigh Quotient: 5.816 (7 iterations)
Rayleigh Quotient: 4.394 (8 iterations)
Rayleigh Quotient: 5.517 (9 iterations)
Rayleigh Quotient: 4.607 (10 iterations)
Rayleigh Quotient: 5.328 (11 iterations)
Rayleigh Quotient: 4.746 (12 iterations)
Rayleigh Quotient: 5.208 (13 iterations)
Rayleigh Quotient: 4.837 (14 iterations)
Rayleigh Quotient: 5.133 (15 iterations)
Rayleigh Quotient: 4.895 (16 iterations)
Rayleigh Quotient: 5.085 (17 iterations)
Rayleigh Quotient: 4.933 (18 iterations)
Rayleigh Quotient: 5.054 (19 iterations)
Rayleigh Quotient: 4.957 (20 iterations)
Rayleigh Quotient: 5.035 (21 iterations)
Rayleigh Quotient: 4.972 (22 iterations)
Rayleigh Quotient: 5.022 (23 iterations)
Rayleigh Quotient: 4.982 (24 iterations)
Rayleigh Quotient: 5.014 

In [67]:
print(f'Absolute error A: {spla.norm(A @ eig_vec_A - eig_val_A * eig_vec_A)}')
print(f'Absolute error B: {spla.norm(B @ eig_vec_B - eig_val_B * eig_vec_B)}')

Absolute error A: 0.00875926554077168
Absolute error B: 4.443150246491174e-16


## Inverse Potenzenmethode mit Shift

**(d) Schreiben Sie nun eine Prozedur, welche einen zusätzlichen Eingabeparameter $\mu$ hat und die inverse Potenzenmethode mit Shift $\mu$ durchführt.**

Zur Lösung der auftretenden LGS verwenden wir eine LR-Zerlegung. Für eine Matrix $A$ erhalten Sie diese über den Befehl, `spla.lu(A)`, welcher drei Matrizen $P,L,R$ (Permutationsmatrix, untere und obere Dreiecksmatrix) zurückgibt, für die $A = PLR$ gilt. ACHTUNG: Aus der VL kennen wir die Zerlegung in der Form $PA=LR$!

Mit dem Befehl `solve_triangular(A,b,lower=True)` bzw. `solve_triangular(A,b,lower=False)` können Sie dann LGS mit einer unteren/oberen Dreiecksmatrix durch Vorwärts- bzw. Rückwärtssubstitution lösen lassen.

In [68]:
def power_iteration_shift(K, A, z0, shift):
    y_k = 1/spla.norm(z0) * z0
    z_k = y_k
    k = 0
    n = np.shape(A)[0]
    M = shift * np.eye(n) - A
    P, L, R = spla.lu(M)
    while k < K:
        # M @ z_k = y_k
        # P L R @ z_k = y_k
        # L R @ z_k = P.T @ y_k
        Rz_k = spla.solve_triangular(L, P.T @ y_k, lower=True)
        z_k = spla.solve_triangular(R, Rz_k, lower=False)
        y_k = 1/spla.norm(z_k) * z_k
        q_k = rayleigh_quot(A, y_k)
        k += 1
        print(f'Rayleigh Quotient: {q_k:.3f} ({k} iterations)')
    return q_k, y_k

**(e) Testen Sie Ihre Prozedur wie oben mit der Matrix $A$. Verwenden Sie als Shift zunächst $\mu = 4$. Was beobachten Sie im Vergleich zu oben? Verwenden Sie anschließend die Shifts $\mu = -3$ und $\mu = 0$. Was passiert und warum?**


In [69]:
print(f'shift: 4')
power_iteration_shift(30, A, np.array([1, 1, 1, 1]), 4)
print(f'shift: -3')
power_iteration_shift(30, A, np.array([1, 1, 1, 1]), -3)
print(f'shift: 0')
power_iteration_shift(30, A, np.array([1, 1, 1, 1]), 0)


shift: 4
Rayleigh Quotient: 4.055 (1 iterations)
Rayleigh Quotient: 5.293 (2 iterations)
Rayleigh Quotient: 4.930 (3 iterations)
Rayleigh Quotient: 5.016 (4 iterations)
Rayleigh Quotient: 4.997 (5 iterations)
Rayleigh Quotient: 5.000 (6 iterations)
Rayleigh Quotient: 5.000 (7 iterations)
Rayleigh Quotient: 5.000 (8 iterations)
Rayleigh Quotient: 5.000 (9 iterations)
Rayleigh Quotient: 5.000 (10 iterations)
Rayleigh Quotient: 5.000 (11 iterations)
Rayleigh Quotient: 5.000 (12 iterations)
Rayleigh Quotient: 5.000 (13 iterations)
Rayleigh Quotient: 5.000 (14 iterations)
Rayleigh Quotient: 5.000 (15 iterations)
Rayleigh Quotient: 5.000 (16 iterations)
Rayleigh Quotient: 5.000 (17 iterations)
Rayleigh Quotient: 5.000 (18 iterations)
Rayleigh Quotient: 5.000 (19 iterations)
Rayleigh Quotient: 5.000 (20 iterations)
Rayleigh Quotient: 5.000 (21 iterations)
Rayleigh Quotient: 5.000 (22 iterations)
Rayleigh Quotient: 5.000 (23 iterations)
Rayleigh Quotient: 5.000 (24 iterations)
Rayleigh Quotien

(np.float64(0.9999999999999607),
 array([ 0.2236068 , -0.67082039, -0.2236068 ,  0.67082039]))

## Rayleigh-Quotienten-Iteration

**(f) Kopieren Sie Ihre Prozedur aus Teil (d) und ändern Sie diese zur Rayleigh-Quotienten-Iteration ab. Testen Sie diese wie in Teil (e). Verwenden Sie auch einmal einen besonders schlechten Shift, z.B. $\mu = 100$.**

Ggf. sollten Sie noch ein Abbruchkriterium ergänzen, z.B. falls $\left\lVert Av-\lambda v \right\rVert_2<10^{-14}$ für die aktuelle Approximation $\lambda,v$ an Eigenwert und Eigenvektor gilt (sonst kann die Matrix $\mu I - A$ irgendwann singulär werden).

In [70]:
def rayleigh_iteration(K, A, z0, shift0):
    shift = shift0
    y_k = 1/spla.norm(z0) * z0
    z_k = y_k
    k = 0
    n = np.shape(A)[0]
    while k < K:
        # M @ z_k = y_k
        # P L R @ z_k = y_k
        # L R @ z_k = P.T @ y_k
        M = shift * np.eye(n) - A
        P, L, R = spla.lu(M)
        Rz_k = spla.solve_triangular(L, P.T @ y_k, lower=True)
        z_k = spla.solve_triangular(R, Rz_k, lower=False)
        y_k = 1/spla.norm(z_k) * z_k
        q_k = rayleigh_quot(A, y_k)
        shift = q_k
        k += 1
        print(f'Rayleigh Quotient: {q_k:.3f} ({k} iterations)')

        norm = spla.norm(A @ y_k - q_k * y_k)
        if norm < 1e-14:
            print(f'Stopping criteria reached after {k} iterations.')
            return q_k, y_k

    return q_k, y_k

In [71]:
rayleigh_iteration(100, A, np.array([1, 1, 1, 1]), 4)

Rayleigh Quotient: 4.055 (1 iterations)
Rayleigh Quotient: 5.293 (2 iterations)
Rayleigh Quotient: 4.930 (3 iterations)
Rayleigh Quotient: 5.016 (4 iterations)
Rayleigh Quotient: 4.997 (5 iterations)
Rayleigh Quotient: 5.000 (6 iterations)
Rayleigh Quotient: 5.000 (7 iterations)
Rayleigh Quotient: 5.000 (8 iterations)
Rayleigh Quotient: 5.000 (9 iterations)
Rayleigh Quotient: 5.000 (10 iterations)
Rayleigh Quotient: 5.000 (11 iterations)
Rayleigh Quotient: 5.000 (12 iterations)
Rayleigh Quotient: 5.000 (13 iterations)
Rayleigh Quotient: 5.000 (14 iterations)
Rayleigh Quotient: 5.000 (15 iterations)
Rayleigh Quotient: 5.000 (16 iterations)
Rayleigh Quotient: 5.000 (17 iterations)
Rayleigh Quotient: 5.000 (18 iterations)
Rayleigh Quotient: 5.000 (19 iterations)
Rayleigh Quotient: 5.000 (20 iterations)
Rayleigh Quotient: 5.000 (21 iterations)
Rayleigh Quotient: 5.000 (22 iterations)
Rayleigh Quotient: 5.000 (23 iterations)
Rayleigh Quotient: 5.000 (24 iterations)
Rayleigh Quotient: 5.000 

(np.float64(5.000000000000006),
 array([-5.77350269e-01, -5.77350269e-01,  5.77350269e-01, -3.33066907e-16]))

In [72]:
rayleigh_iteration(100, A, np.array([1, 1, 1, 1]), 100)


Rayleigh Quotient: 8.300 (1 iterations)
Rayleigh Quotient: 10.443 (2 iterations)
Rayleigh Quotient: 11.526 (3 iterations)
Rayleigh Quotient: 11.867 (4 iterations)
Rayleigh Quotient: 11.770 (5 iterations)
Rayleigh Quotient: 11.444 (6 iterations)
Rayleigh Quotient: 11.018 (7 iterations)
Rayleigh Quotient: 10.563 (8 iterations)
Rayleigh Quotient: 10.114 (9 iterations)
Rayleigh Quotient: 9.691 (10 iterations)
Rayleigh Quotient: 9.301 (11 iterations)
Rayleigh Quotient: 8.944 (12 iterations)
Rayleigh Quotient: 8.621 (13 iterations)
Rayleigh Quotient: 8.330 (14 iterations)
Rayleigh Quotient: 8.066 (15 iterations)
Rayleigh Quotient: 7.829 (16 iterations)
Rayleigh Quotient: 7.614 (17 iterations)
Rayleigh Quotient: 7.420 (18 iterations)
Rayleigh Quotient: 7.244 (19 iterations)
Rayleigh Quotient: 7.084 (20 iterations)
Rayleigh Quotient: 6.938 (21 iterations)
Rayleigh Quotient: 6.805 (22 iterations)
Rayleigh Quotient: 6.684 (23 iterations)
Rayleigh Quotient: 6.573 (24 iterations)
Rayleigh Quotient

(np.float64(5.032056172814664),
 array([ 0.57916273,  0.5736976 , -0.57912868,  0.0071805 ]))

In [73]:
rayleigh_iteration(30, A, np.array([1, 1, 1, 1]), 0)


Rayleigh Quotient: 0.097 (1 iterations)
Rayleigh Quotient: 1.167 (2 iterations)
Rayleigh Quotient: 0.985 (3 iterations)
Rayleigh Quotient: 1.065 (4 iterations)
Rayleigh Quotient: 1.007 (5 iterations)
Rayleigh Quotient: 0.998 (6 iterations)
Rayleigh Quotient: 1.001 (7 iterations)
Rayleigh Quotient: 0.999 (8 iterations)
Rayleigh Quotient: 1.000 (9 iterations)
Rayleigh Quotient: 1.000 (10 iterations)
Rayleigh Quotient: 1.000 (11 iterations)
Rayleigh Quotient: 1.000 (12 iterations)
Rayleigh Quotient: 1.000 (13 iterations)
Rayleigh Quotient: 1.000 (14 iterations)
Rayleigh Quotient: 1.000 (15 iterations)
Rayleigh Quotient: 1.000 (16 iterations)
Rayleigh Quotient: 1.000 (17 iterations)
Rayleigh Quotient: 1.000 (18 iterations)
Rayleigh Quotient: 1.000 (19 iterations)
Rayleigh Quotient: 1.000 (20 iterations)
Rayleigh Quotient: 1.000 (21 iterations)
Rayleigh Quotient: 1.000 (22 iterations)
Rayleigh Quotient: 1.000 (23 iterations)
Rayleigh Quotient: 1.000 (24 iterations)
Rayleigh Quotient: 1.000 

(np.float64(0.9999999999999607),
 array([ 0.2236068 , -0.67082039, -0.2236068 ,  0.67082039]))